name: GitHub Actions Demo

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Context
        run: |
        echo "Event: ${{ github.event.name }}"
        echo "Branch: ${{ github.ref }} in repository ${{ github.repository }}"

      - uses: actions/checkout@v4

      - name: Files
        run: |
          ls -lah
